/*
 Navicat Premium Data Transfer

 Source Server         : local-mysql
 Source Server Type    : MySQL
 Source Server Version : 100413
 Source Host           : localhost:3306
 Source Schema         : odontogram

 Target Server Type    : MySQL
 Target Server Version : 100413
 File Encoding         : 65001

 Date: 02/01/2022 20:26:44
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for t_log_aktifitas
-- ----------------------------
DROP TABLE IF EXISTS `t_log_aktifitas`;
CREATE TABLE `t_log_aktifitas`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_user` int(11) NULL DEFAULT NULL,
  `url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `aksi` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `new_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `old_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  `updated_at` datetime(0) NULL DEFAULT NULL,
  `deleted_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `id_user`(`id_user`) USING BTREE,
  CONSTRAINT `t_log_aktifitas_ibfk_1` FOREIGN KEY (`id_user`) REFERENCES `m_user` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB AUTO_INCREMENT = 49 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of t_log_aktifitas
-- ----------------------------
INSERT INTO `t_log_aktifitas` VALUES (1, 1, 'http://localhost/odontogram/data_pasien/delete_data?', 'HAPUS DATA PASIEN', NULL, 'null', '2022-01-01 18:33:36', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (2, 1, 'http://localhost/odontogram/data_pasien/delete_data?', 'HAPUS DATA PASIEN', NULL, 'null', '2022-01-01 18:33:46', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (3, 1, 'http://localhost/odontogram/data_pasien/delete_data?', 'HAPUS DATA PASIEN', NULL, '{\"id\":\"4\",\"no_rm\":\"YA.2012.02.0001\",\"nama\":\"ANDY WAN\",\"tempat_lahir\":\"surabaya\",\"tanggal_lahir\":\"1985-03-02\",\"nik\":\"882712121881819\",\"jenis_kelamin\":\"L\",\"suku\":null,\"pekerjaan\":null,\"alamat_rumah\":\"Jl. A Yuni 201 Surabaya\",\"telp_rumah\":null,\"alamat_kantor\":null,\"hp\":\"071827182718\",\"is_aktif\":\"1\",\"created_at\":\"2021-12-16 01:03:00\",\"updated_at\":\"2022-01-01 18:15:36\",\"deleted_at\":\"2022-01-01 18:33:46\",\"file_ktp\":null}', '2022-01-01 18:34:03', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (4, 1, 'http://localhost/odontogram/login/proses?', 'LOGIN', NULL, NULL, '2022-01-01 21:46:35', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (5, 1, 'http://localhost/odontogram/reg_pasien/simpan_data?', 'TAMBAH DATA REGISTRASI', '{\"id_pasien\":\"8\",\"tanggal_reg\":\"2022-01-01\",\"jam_reg\":\"22:08:00\",\"id_pegawai\":\"8\",\"is_asuransi\":null,\"nama_asuransi\":null,\"no_asuransi\":null,\"id_klinik\":\"3\",\"umur\":\"54\",\"id_pemetaan\":\"5\",\"id_layanan\":\"7\",\"id\":6,\"no_reg\":\"000.000.000.006\",\"created_at\":\"2022-01-01 22:08:21\"}', NULL, '2022-01-01 22:08:21', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (6, 1, 'http://localhost/odontogram/reg_pasien/simpan_data?', 'UBAH DATA REGISTRASI', '{\"id\":\"6\",\"id_pasien\":\"8\",\"tanggal_reg\":\"2022-01-01\",\"jam_reg\":\"22:20:00\",\"id_pegawai\":\"8\",\"is_asuransi\":null,\"nama_asuransi\":null,\"no_asuransi\":null,\"id_klinik\":\"3\",\"umur\":\"54\",\"id_pemetaan\":\"5\",\"id_layanan\":\"3\",\"updated_at\":\"2022-01-01 22:09:46\"}', '{\"id\":\"6\",\"id_klinik\":\"3\",\"id_layanan\":\"7\",\"id_pasien\":\"8\",\"no_reg\":\"000.000.000.006\",\"tanggal_reg\":\"2022-01-01\",\"jam_reg\":\"22:08:00\",\"estimasi_selesai\":null,\"id_pegawai\":\"8\",\"is_asuransi\":null,\"umur\":\"54\",\"id_pemetaan\":\"5\",\"nama_asuransi\":null,\"no_asuransi\":null,\"is_pulang\":null,\"tanggal_pulang\":null,\"jam_pulang\":null,\"created_at\":\"2022-01-01 22:08:21\",\"updated_at\":null,\"deleted_at\":null}', '2022-01-01 22:09:46', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (7, 1, 'http://localhost/odontogram/reg_pasien/delete_data?', 'HAPUS DATA REGISTRASI', NULL, '{\"id\":\"6\",\"id_klinik\":\"3\",\"id_layanan\":\"3\",\"id_pasien\":\"8\",\"no_reg\":\"000.000.000.006\",\"tanggal_reg\":\"2022-01-01\",\"jam_reg\":\"22:20:00\",\"estimasi_selesai\":null,\"id_pegawai\":\"8\",\"is_asuransi\":null,\"umur\":\"54\",\"id_pemetaan\":\"5\",\"nama_asuransi\":null,\"no_asuransi\":null,\"is_pulang\":null,\"tanggal_pulang\":null,\"jam_pulang\":null,\"created_at\":\"2022-01-01 22:08:21\",\"updated_at\":\"2022-01-01 22:09:46\",\"deleted_at\":null}', '2022-01-01 22:10:41', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (8, 1, 'http://localhost/odontogram/login/logout_proc?', 'LOGOUT', NULL, NULL, '2022-01-01 22:12:30', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (9, 5, 'http://localhost/odontogram/login/confirm_middle_login?', 'LOGIN', NULL, NULL, '2022-01-01 22:12:40', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (10, 5, 'http://localhost/odontogram/login/logout_proc?', 'LOGOUT', NULL, NULL, '2022-01-01 22:12:56', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (11, 1, 'http://localhost/odontogram/login/proses?', 'LOGIN', NULL, NULL, '2022-01-01 22:13:03', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (12, 1, 'http://localhost/odontogram/reg_pasien/simpan_data?', 'TAMBAH DATA REGISTRASI', '{\"id_pasien\":\"11\",\"tanggal_reg\":\"2022-01-01\",\"jam_reg\":\"22:13:15\",\"id_pegawai\":\"6\",\"is_asuransi\":null,\"nama_asuransi\":null,\"no_asuransi\":null,\"id_klinik\":\"4\",\"umur\":\"36\",\"id_pemetaan\":\"4\",\"id_layanan\":\"3\",\"id\":7,\"no_reg\":\"000.000.000.007\",\"created_at\":\"2022-01-01 22:13:40\"}', NULL, '2022-01-01 22:13:40', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (13, 1, 'http://localhost/odontogram/login/logout_proc?', 'LOGOUT', NULL, NULL, '2022-01-01 22:13:53', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (14, 5, 'http://localhost/odontogram/login/confirm_middle_login?', 'LOGIN', NULL, NULL, '2022-01-01 22:14:04', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (15, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_anamnesa?', 'TAMBAH DATA ANAMNESA (REKAM MEDIK)', '{\"id_pasien\":\"11\",\"id_pegawai\":\"6\",\"id_reg\":\"7\",\"anamnesa\":\"<p>1. Lombok 1kg<\\/p>\\n\\n<p>2. Gula 2kg<\\/p>\\n\\n<p>3. micin 3 ons<\\/p>\\n\",\"id\":2,\"tanggal\":\"2022-01-01\",\"created_at\":\"2022-01-01 22:32:15\"}', NULL, '2022-01-01 22:32:15', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (16, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_diagnosa?', 'TAMBAH DATA DIAGNOSA (REKAM MEDIK)', '{\"id_pasien\":\"11\",\"id_pegawai\":\"6\",\"id_reg\":\"7\",\"id_user_adm\":\"5\",\"tanggal\":\"2022-01-01\",\"created_at\":\"2022-01-01 22:39:11\"}', NULL, '2022-01-01 22:39:11', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (17, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_diagnosa?', 'TAMBAH DATA DIAGNOSA DETAIL (REKAM MEDIK)', '{\"id_t_diagnosa\":\"3\",\"id_diagnosa\":\"4\",\"gigi\":\"3\",\"created_at\":\"2022-01-01 22:39:11\"}', NULL, '2022-01-01 22:39:11', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (18, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_diagnosa?', 'TAMBAH DATA DIAGNOSA DETAIL (REKAM MEDIK)', '{\"id_t_diagnosa\":\"3\",\"id_diagnosa\":\"1\",\"gigi\":\"3\",\"created_at\":\"2022-01-01 22:42:07\"}', NULL, '2022-01-01 22:42:07', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (19, 5, 'http://localhost/odontogram/rekam_medik/delete_data_diagnosa_det?', 'HAPUS DATA DIAGNOSA DETAIL (REKAM MEDIK)', NULL, '{\"id\":\"6\",\"id_t_diagnosa\":\"3\",\"id_diagnosa\":\"1\",\"gigi\":\"3\",\"created_at\":\"2022-01-01 22:42:07\",\"updated_at\":null,\"deleted_at\":null}', '2022-01-01 22:43:54', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (20, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_tindakan?', 'TAMBAH DATA TINDAKAN (REKAM MEDIK)', '{\"id\":5,\"id_pasien\":\"11\",\"id_pegawai\":\"6\",\"id_reg\":\"7\",\"id_user_adm\":\"5\",\"tanggal\":\"2022-01-01\",\"created_at\":\"2022-01-01 22:57:54\"}', NULL, '2022-01-01 22:57:54', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (21, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_tindakan?', 'TAMBAH DATA TINDAKAN DETAIL (REKAM MEDIK)', '{\"id\":9,\"id_t_tindakan\":\"5\",\"id_tindakan\":\"1\",\"gigi\":\"5\",\"harga\":95000,\"diskon_persen\":\"5\",\"diskon_nilai\":5000,\"harga_bruto\":100000,\"keterangan\":\"\",\"created_at\":\"2022-01-01 22:57:54\"}', NULL, '2022-01-01 22:57:54', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (22, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_tindakan?', 'TAMBAH DATA TINDAKAN DETAIL (REKAM MEDIK)', '{\"id\":10,\"id_t_tindakan\":\"5\",\"id_tindakan\":\"4\",\"gigi\":\"all\",\"harga\":80000,\"diskon_persen\":\"20\",\"diskon_nilai\":20000,\"harga_bruto\":100000,\"keterangan\":\"\",\"created_at\":\"2022-01-01 22:58:00\"}', NULL, '2022-01-01 22:58:00', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (23, 5, 'http://localhost/odontogram/rekam_medik/delete_data_tindakan_det?', 'HAPUS DATA TINDAKAN DETAIL (REKAM MEDIK)', NULL, '{\"id\":\"9\",\"id_t_tindakan\":\"5\",\"id_tindakan\":\"1\",\"gigi\":\"5\",\"harga\":\"95000.00\",\"keterangan\":\"\",\"created_at\":\"2022-01-01 22:57:54\",\"updated_at\":null,\"deleted_at\":null,\"diskon_persen\":\"5\",\"diskon_nilai\":\"5000.00\",\"harga_bruto\":\"100000.00\",\"id_reg\":\"7\",\"id_pegawai\":\"6\"}', '2022-01-01 22:58:52', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (24, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_logistik?', 'TAMBAH DATA LOGISTIK (REKAM MEDIK)', '{\"id\":2,\"id_pasien\":\"11\",\"id_pegawai\":\"6\",\"id_reg\":\"7\",\"id_user_adm\":\"5\",\"tanggal\":\"2022-01-01\",\"created_at\":\"2022-01-01 23:06:42\"}', NULL, '2022-01-01 23:06:42', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (25, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_logistik?', 'TAMBAH DATA LOGISTIK DETAIL (REKAM MEDIK)', '{\"id\":2,\"id_t_logistik\":\"2\",\"id_logistik\":\"3\",\"qty\":\"6\",\"harga\":0,\"subtotal\":0,\"created_at\":\"2022-01-01 23:06:42\"}', NULL, '2022-01-01 23:06:42', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (26, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_logistik?', 'TAMBAH DATA LOGISTIK DETAIL (REKAM MEDIK)', '{\"id\":3,\"id_t_logistik\":\"2\",\"id_logistik\":\"3\",\"qty\":\"6\",\"harga\":0,\"subtotal\":0,\"created_at\":\"2022-01-01 23:06:43\"}', NULL, '2022-01-01 23:06:43', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (27, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_logistik?', 'TAMBAH DATA LOGISTIK DETAIL (REKAM MEDIK)', '{\"id\":4,\"id_t_logistik\":\"2\",\"id_logistik\":\"4\",\"qty\":\"6\",\"harga\":0,\"subtotal\":0,\"created_at\":\"2022-01-01 23:07:54\"}', NULL, '2022-01-01 23:07:54', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (28, 5, 'http://localhost/odontogram/rekam_medik/delete_data_logistik_det?', 'HAPUS DATA LOGISTIK DETAIL (REKAM MEDIK)', NULL, '{\"id\":\"4\",\"id_t_logistik\":\"2\",\"id_logistik\":\"4\",\"qty\":\"6\",\"harga\":\"0.00\",\"subtotal\":\"0.00\",\"created_at\":\"2022-01-01 23:07:54\",\"updated_at\":null,\"deleted_at\":null,\"id_reg\":\"7\",\"id_pegawai\":\"6\"}', '2022-01-01 23:08:05', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (29, 5, 'http://localhost/odontogram/rekam_medik/save_odontogram?', 'TAMBAH DATA GAMBAR ODONTO (REKAM MEDIK)', '{\"gambar\":\"7.png\",\"id_reg\":\"7\"}', NULL, '2022-01-01 23:13:08', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (30, 5, 'http://localhost/odontogram/rekam_medik/save_odontogram?', 'UBAH DATA GAMBAR ODONTO (REKAM MEDIK)', '{\"gambar\":\"7.png\",\"id_reg\":\"7\"}', '{\"id_reg\":\"7\",\"gambar\":\"7.png\",\"id\":\"3\",\"sebelas\":null,\"dua_belas\":null,\"tiga_belas\":null,\"empat_belas\":null,\"lima_belas\":null,\"enam_belas\":null,\"tujuh_belas\":null,\"delapan_belas\":null,\"dua_satu\":null,\"dua_dua\":null,\"dua_tiga\":null,\"dua_empat\":null,\"dua_lima\":null,\"dua_enam\":null,\"dua_tujuh\":null,\"dua_delapan\":null,\"tiga_satu\":null,\"tiga_dua\":null,\"tiga_tiga\":null,\"tiga_empat\":null,\"tiga_lima\":null,\"tiga_enam\":null,\"tiga_tujuh\":null,\"tiga_delapan\":null,\"empat_satu\":null,\"empat_dua\":null,\"empat_tiga\":null,\"empat_empat\":null,\"empat_lima\":null,\"empat_enam\":null,\"empat_tujuh\":null,\"empat_delapan\":null,\"occlusi\":null,\"torus_palatinus\":null,\"torus_mandibularis\":null,\"palatum\":null,\"diastema\":null,\"keterangan_diastema\":null,\"gigi_anomali\":null,\"keterangan_gigi_anomali\":null,\"d\":null,\"m\":null,\"f\":null,\"jumlah_foto\":null,\"jumlah_rontgen\":null,\"lain_lain\":null,\"satuan_jumlah_foto\":null,\"satuan_jumlah_rontgen\":null}', '2022-01-01 23:13:45', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (31, 5, 'http://localhost/odontogram/rekam_medik/save_formulir_odonto?id_reg=7', 'UBAH DATA FORM ODONTO (REKAM MEDIK)', '{\"sebelas\":\"\",\"dua_belas\":\"\",\"tiga_belas\":\"\",\"empat_belas\":\"\",\"lima_belas\":\"\",\"enam_belas\":\"\",\"tujuh_belas\":\"\",\"delapan_belas\":\"\",\"dua_satu\":\"\",\"dua_dua\":\"\",\"dua_tiga\":\"\",\"dua_empat\":\"\",\"dua_lima\":\"\",\"dua_enam\":\"\",\"dua_tujuh\":\"\",\"dua_delapan\":\"\",\"tiga_satu\":\"\",\"tiga_dua\":\"\",\"tiga_tiga\":\"\",\"tiga_empat\":\"\",\"tiga_lima\":\"\",\"tiga_enam\":\"\",\"tiga_tujuh\":\"\",\"tiga_delapan\":\"\",\"empat_satu\":\"\",\"empat_dua\":\"\",\"empat_tiga\":\"\",\"empat_empat\":\"\",\"empat_lima\":\"\",\"empat_enam\":\"\",\"empat_tujuh\":\"\",\"empat_delapan\":\"\",\"occlusi\":\"\",\"torus_palatinus\":null,\"torus_mandibularis\":null,\"palatum\":\"\",\"diastema\":null,\"keterangan_diastema\":\"\",\"gigi_anomali\":null,\"keterangan_gigi_anomali\":\"\",\"lain_lain\":\"\",\"d\":\"\",\"m\":\"\",\"f\":\"\",\"jumlah_rontgen\":\"\",\"jumlah_foto\":\"\"}', '{\"id_reg\":\"7\",\"gambar\":\"7.png\",\"id\":\"3\",\"sebelas\":null,\"dua_belas\":null,\"tiga_belas\":null,\"empat_belas\":null,\"lima_belas\":null,\"enam_belas\":null,\"tujuh_belas\":null,\"delapan_belas\":null,\"dua_satu\":null,\"dua_dua\":null,\"dua_tiga\":null,\"dua_empat\":null,\"dua_lima\":null,\"dua_enam\":null,\"dua_tujuh\":null,\"dua_delapan\":null,\"tiga_satu\":null,\"tiga_dua\":null,\"tiga_tiga\":null,\"tiga_empat\":null,\"tiga_lima\":null,\"tiga_enam\":null,\"tiga_tujuh\":null,\"tiga_delapan\":null,\"empat_satu\":null,\"empat_dua\":null,\"empat_tiga\":null,\"empat_empat\":null,\"empat_lima\":null,\"empat_enam\":null,\"empat_tujuh\":null,\"empat_delapan\":null,\"occlusi\":null,\"torus_palatinus\":null,\"torus_mandibularis\":null,\"palatum\":null,\"diastema\":null,\"keterangan_diastema\":null,\"gigi_anomali\":null,\"keterangan_gigi_anomali\":null,\"d\":null,\"m\":null,\"f\":null,\"jumlah_foto\":null,\"jumlah_rontgen\":null,\"lain_lain\":null,\"satuan_jumlah_foto\":null,\"satuan_jumlah_rontgen\":null}', '2022-01-01 23:18:15', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (32, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_kamera?', 'TAMBAH DATA X-RAY (REKAM MEDIK)', '{\"id_pasien\":\"11\",\"id_pegawai\":\"6\",\"id_reg\":\"7\",\"id_user_adm\":\"5\",\"tanggal\":\"2022-01-01\",\"created_at\":\"2022-01-01 23:20:21\"}', NULL, '2022-01-01 23:20:21', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (33, 5, 'http://localhost/odontogram/rekam_medik/simpan_form_kamera?', 'TAMBAH DATA X-RAY DETAIL (REKAM MEDIK)', '{\"id_t_kamera\":\"2\",\"keterangan\":\"k\",\"nama_gambar\":\"7_1154652277.jpg\",\"created_at\":\"2022-01-01 23:20:21\"}', NULL, '2022-01-01 23:20:21', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (34, 5, 'http://localhost/odontogram/login/confirm_middle_login?', 'LOGIN', NULL, NULL, '2022-01-02 08:05:00', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (35, 5, 'http://localhost/odontogram/rekam_medik/pulangkan_pasien?', 'REKAM MEDIK SELESAI', '{\"tanggal_pulang\":\"2022-01-02\",\"jam_pulang\":\"08:25:56\",\"is_pulang\":1,\"updated_at\":\"2022-01-02 08:25:56\",\"id\":\"7\"}', NULL, '2022-01-02 08:25:56', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (36, 5, 'http://localhost/odontogram/rekam_medik/batal_pulangkan_pasien?', 'PEMBATALAN REKAM MEDIK SELESAI', '{\"tanggal_pulang\":\"2022-01-02\",\"jam_pulang\":\"08:26:13\",\"is_pulang\":1,\"updated_at\":\"2022-01-02 08:26:13\",\"id\":\"7\"}', NULL, '2022-01-02 08:26:13', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (37, 5, 'http://localhost/odontogram/rekam_medik/pulangkan_pasien?', 'REKAM MEDIK SELESAI', '{\"tanggal_pulang\":\"2022-01-02\",\"jam_pulang\":\"08:26:38\",\"is_pulang\":1,\"updated_at\":\"2022-01-02 08:26:38\",\"id\":\"7\"}', NULL, '2022-01-02 08:26:38', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (38, 5, 'http://localhost/odontogram/login/logout_proc?', 'LOGOUT', NULL, NULL, '2022-01-02 08:26:48', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (39, 4, 'http://localhost/odontogram/login/confirm_middle_login?', 'LOGIN', NULL, NULL, '2022-01-02 08:27:01', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (40, 4, 'http://localhost/odontogram/pembayaran/simpan_data?', 'TAMBAH DATA PEMBAYARAN', '{\"id\":3,\"id_reg\":\"7\",\"tanggal\":\"2022-01-02\",\"id_user\":\"4\",\"disc_persen\":\"0\",\"disc_rp\":\"\",\"disc_nilai\":\"0\",\"total_bruto\":\"80000\",\"total_nett\":\"80000\",\"is_locked\":1,\"rupiah_bayar\":\"100000.00\",\"rupiah_kembali\":\"20000.00\",\"kode\":\"INV-202201-0001\",\"is_cash\":1,\"reff_trans_kredit\":null,\"created_at\":\"2022-01-02 09:29:51\"}', NULL, '2022-01-02 09:29:51', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (41, 4, 'http://localhost/odontogram/login/logout_proc?', 'LOGOUT', NULL, NULL, '2022-01-02 09:30:24', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (42, 1, 'http://localhost/odontogram/login/proses?', 'LOGIN', NULL, NULL, '2022-01-02 09:30:43', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (43, 1, 'http://localhost/odontogram/login/proses?', 'LOGIN', NULL, NULL, '2022-01-02 17:38:45', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (44, 1, 'http://localhost/odontogram/login/logout_proc?', 'LOGOUT', NULL, NULL, '2022-01-02 18:01:24', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (45, 4, 'http://localhost/odontogram/login/confirm_middle_login?', 'LOGIN', NULL, NULL, '2022-01-02 18:08:33', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (46, 4, 'http://localhost/odontogram/data_pasien/simpan_data?', 'TAMBAH DATA PASIEN', '{\"nama\":\"NUR CAHYONO\",\"nik\":\"19281928192812\",\"tempat_lahir\":\"SURABAYA\",\"tanggal_lahir\":\"1990-01-01\",\"jenis_kelamin\":\"L\",\"suku\":null,\"pekerjaan\":null,\"hp\":\"089612897848\",\"telp_rumah\":null,\"alamat_rumah\":\"JALAN JALAN\",\"alamat_kantor\":null,\"id\":13,\"no_rm\":\"NU.1990.01.0001\",\"created_at\":\"2022-01-02 18:13:46\",\"is_aktif\":1}', NULL, '2022-01-02 18:13:46', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (47, 4, 'http://localhost/odontogram/data_pasien/simpan_data?', 'TAMBAH DATA MEDIK', '{\"gol_darah\":\"Z\",\"tekanan_darah\":\"HYPERTENSI\",\"tekanan_darah_val\":\"2\",\"penyakit_jantung\":\"0\",\"diabetes\":\"0\",\"haemopilia\":\"0\",\"hepatitis\":\"0\",\"gastring\":\"0\",\"penyakit_lainnya\":\"0\",\"alergi_obat\":\"0\",\"alergi_obat_val\":null,\"alergi_makanan\":\"0\",\"alergi_makanan_val\":null,\"id\":17,\"id_pasien\":13,\"created_at\":\"2022-01-02 18:13:46\"}', NULL, '2022-01-02 18:13:46', NULL, NULL);
INSERT INTO `t_log_aktifitas` VALUES (48, 4, 'http://localhost/odontogram/reg_pasien/simpan_data?', 'TAMBAH DATA REGISTRASI', '{\"id_pasien\":\"13\",\"tanggal_reg\":\"2022-01-02\",\"jam_reg\":\"18:13:45\",\"id_pegawai\":\"1\",\"is_asuransi\":null,\"nama_asuransi\":null,\"no_asuransi\":null,\"id_klinik\":\"4\",\"umur\":\"32\",\"id_pemetaan\":\"4\",\"id_layanan\":\"1\",\"id\":8,\"no_reg\":\"000.000.000.008\",\"created_at\":\"2022-01-02 18:14:07\"}', NULL, '2022-01-02 18:14:07', NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
